# Copyright Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT
"""Pytest configuration for Tensile/client harness tests.

Defines haveDeps, requires_deps, and requires_gfx950. The chip is detected
lazily at test-setup time, not at collection time, so that HIP initialization
does not happen before session fixtures (important for M11 ROCprofiler-SDK).

Also provides --generate-parity-report: when passed, writes
Tensile/client/parity_report.md at session end with the data collected by
test_parity.py via config._parityData.
"""

import functools
import os

import pytest

try:
    import amdgpu_exec  # noqa: F401
    haveDeps = True
except ImportError:
    haveDeps = False

# IMPORTANT: tensilelite_profiler must be imported before any HIP call.
# The try/except here runs at collection time, which is safe because no
# HIP call has happened yet (get_chip() is lazy and deferred to test-setup).
try:
    import tensilelite_profiler as _profMod
    if not hasattr(_profMod, 'initialize'):
        raise ImportError("tensilelite_profiler C extension not installed")
    tensileliteProfilerAvailable = True
except (ImportError, RuntimeError):
    tensileliteProfilerAvailable = False

requires_deps = pytest.mark.skipif(not haveDeps, reason="amdgpu_exec not installed")

# IMPORTANT: do NOT call get_chip() here. get_chip() triggers HIP initialization
# on first use. A module-level call runs during test COLLECTION, which would
# initialize HIP before the session-scoped profiler-import fixture in M11 runs
# and break rocprofiler_force_configure. Keep this as a plain marker and resolve
# the chip lazily in pytest_runtest_setup instead.
requires_gfx950 = pytest.mark.requires_gfx950
requires_rocprof = pytest.mark.requires_rocprof


@functools.lru_cache(maxsize=1)
def _currentChip() -> str:
    from amdgpu_exec import get_chip
    return get_chip()


def pytest_addoption(parser):
    """Add --generate-parity-report flag (opt-in; not in addopts)."""
    parser.addoption(
        "--generate-parity-report",
        action="store_true",
        default=False,
        help=(
            "Generate Tensile/client/parity_report.md after the test session. "
            "Data is collected by test_parity.py via config._parityData."
        ),
    )


def pytest_configure(config):
    config.addinivalue_line("markers", "requires_gfx950: run only on a gfx950 GPU")
    config.addinivalue_line(
        "markers",
        "requires_rocprof: run only when tensilelite_profiler is available",
    )
    # Initialize parity data storage, used by test_parity.py.
    config._parityData = {
        "features": [],   # list of (feature, status, evidence) tuples
        "gflops": [],     # list of (feature, problemSize, pyGflops, cppGflops) tuples
        "discrepancies": [],  # list of (feature, message) tuples
    }


def pytest_runtest_setup(item):
    if item.get_closest_marker("requires_gfx950") is not None:
        if not haveDeps:
            pytest.skip("amdgpu_exec not installed")
        if _currentChip() != "gfx950":
            pytest.skip("requires gfx950 GPU")
    if item.get_closest_marker("requires_rocprof") is not None:
        if not tensileliteProfilerAvailable:
            pytest.skip("tensilelite_profiler not available")


def _formatGflopsTable(rows):
    """Format a GFLOPS comparison table for the parity report."""
    lines = [
        "| Problem | Python GFLOPS | C++ GFLOPS | Delta% |",
        "|---------|--------------|------------|--------|",
    ]
    for feature, size, pyGf, cppGf in rows:
        sizeStr = f"{feature} {size}"
        pyStr = f"{pyGf:.1f}" if pyGf is not None else "N/A"
        cppStr = f"{cppGf:.1f}" if cppGf is not None else "N/A (blocked)"
        if pyGf is not None and cppGf is not None:
            delta = 100.0 * (pyGf - cppGf) / cppGf
            deltaStr = f"{delta:+.1f}%"
        else:
            deltaStr = "N/A"
        lines.append(f"| {sizeStr} | {pyStr} | {cppStr} | {deltaStr} |")
    return "\n".join(lines)


def _formatFeatureTable(rows):
    """Format a feature coverage table for the parity report."""
    lines = [
        "| Feature | Status | Evidence |",
        "|---------|--------|----------|",
    ]
    for feature, status, evidence in rows:
        lines.append(f"| {feature} | {status} | {evidence} |")
    return "\n".join(lines)


def _writeParityReport(data, reportPath):
    """Write parity_report.md from collected test data."""
    featureTable = _formatFeatureTable(data["features"]) if data["features"] else "_no data collected_"
    gflopsTable = _formatGflopsTable(data["gflops"]) if data["gflops"] else "_no GFLOPS data collected_"

    discrepancies = data["discrepancies"]
    if discrepancies:
        discrepancyLines = "\n".join(f"- **{f}**: {msg}" for f, msg in discrepancies)
    else:
        discrepancyLines = "_None recorded within stated tolerances._"

    content = f"""# TensileLite Python Harness Parity Report

**Generated by:** `pytest --generate-parity-report`
**Regenerate:** `tox -e unit -- Tensile/client/tests/test_parity.py --generate-parity-report`

> This file is generated output — do not edit by hand. It goes stale when M1–M12 change.
> Re-run the command above to refresh it.

## Feature Coverage

{featureTable}

## GFLOPS Comparison (Python vs C++ client)

{gflopsTable}

**Note on C++ reference:** The C++ `tensilelite-client` requires a pre-built solution
library (TensileLibrary.yaml + .co/.hsaco) from the full Tensile 3-phase pipeline. These
artifacts were not available at M13 implementation time. See
`Tensile/client/tests/fixtures/cpp_client_reference_cmd.txt` for the commands to generate
real C++ reference data. Until then, C++ values show "N/A (blocked)".

Tolerance thresholds: ±5% for all sizes (CI-robustness widened from plan's ±2%/±5%).

## Remaining Discrepancies

{discrepancyLines}
"""
    os.makedirs(os.path.dirname(reportPath), exist_ok=True)
    with open(reportPath, "w") as fh:
        fh.write(content)


def pytest_sessionfinish(session, exitstatus):
    """Write parity_report.md if --generate-parity-report was passed."""
    if not session.config.getoption("--generate-parity-report", default=False):
        return
    data = getattr(session.config, "_parityData", None)
    if data is None:
        return
    thisDir = os.path.dirname(__file__)
    clientDir = os.path.dirname(thisDir)
    reportPath = os.path.join(clientDir, "parity_report.md")
    _writeParityReport(data, reportPath)
    print(f"\nparity_report.md written to: {reportPath}")
